### ISSUE TITLE
how can test single image captioning

### ISSUE THREAD

**Issue by msachenko908** [daqingliu/CAVP#4]
I've trained model
I think its result is good
But i can't test it with my own image in windows 10
How can i do?

**Comment by daqingliu** [comment]
Unfortunately, this repo doesn't support it yet, since it is created just for research.
If you want to generate captions on your own image, I recommend the awesome repo [ImageCaptioning.pytorch](https://github.com/ruotianluo/ImageCaptioning.pytorch).

**Comment by aicsoft115** [comment]
thanks for your reply

can i test in ImageCaptioning.pytorch with cavp model.pth and infos.json
infos_path parameter is different
if it is available,could you tell me how should i do more detaily?

**Comment by msachenko908** [comment]
thanks for your reply
i've tried,but failed
infos_path parameter is different
can i test it in ImageCaptioning.pytorch with cavp model.pth and infos.json
if it is available,please let me know how can i do more detaily

**Comment by daqingliu** [comment]
@msachenko908, the biggest problem is the image feature extraction. Since CAVP uses the bottom-up features while Ruotian using the resnet features, it couldn't directly employ CAVP model to ImageCaptioning.pytorch.
If you want to do so, you could either train another CAVP model with resnet feature or extract bottom-up features for your own images.

**Comment by msachenko908** [comment]
I want to test image caption generating
how can i test my own img with cavp model?
and it is available to convert to tensorflow?

**Comment by daqingliu** [comment]
Sorry for the late reply.
To test your own img with cavp model you should extract img features by  [bottom-up-attention](https://github.com/peteanderson80/bottom-up-attention) and then generate sentences.
It is available to convert to tensorflow with the help of any converting tools, e.g., [onnx](https://github.com/onnx/tutorials).
